### ISSUE TITLE
Missing Client Secret

### ISSUE THREAD

**Issue by jmwyds** [kyle-kelly/MMM-lyft#4]
Hi Kyle,

I really like your module and I made a lyft application on the lyft developer site to get my client ID & secret. However, I can't find the client secret anywhere. Is there something that I'm missing?
Apologies as I know this isn't an issue with your repo, but I was hoping you might be able to guide me to where I should look for that secret. Thank you!

Best, Jack

**Comment by jmwyds** [comment]
![clientIdLyft](https://user-images.githubusercontent.com/26585685/78737617-f20a5f80-791d-11ea-9fb6-098e675fc8d7.PNG)

I'm not sure if this note on the lyft developer site means anything

**Comment by 69degrees** [comment]
I loved this app too. Unfortunately, as you can see in that message "...Lyft made changes to its developer platform. As a result, this application no longer has access to the API platform."

This module has been deprecated. I would suggest reaching out to Lyft and trying to get them to partner with MagicMirror for some official app. Otherwise we're dead in the water and there's nothing we can do. Sorry.

**Comment by jmwyds** [comment]
@69degrees I was holding out hope that maybe I had just done something incorrectly. Sad! Well, thank you for the quick and informative response.

Best,
Jack

**Comment by chrismv48** [comment]
Can we put a deprecation notice on the README about this please?

**Comment by kyle-kelly** [comment]
Done. @chrismv48
